server:
  port: 8081
spring:
  thymeleaf:
    cache: false

#---
#spring:
#  security:
#    user:
#      name: u
#      password: u

logging:
  level:
    org.springframework.web: trace
    org.springframework.security: trace
    cn.com.taiji.learn.sshelloworld: DEBUG

---
# Persistence
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      javax.persistence.validation.mode: none
  h2:
    console:
      enabled: true
  datasource:
    initialization-mode: ALWAYS
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
